LQWeb/App/urls.py
from django.conf.urls import url

from App.views import *

urlpatterns = [
	#zhuye
	url(r'^index/', index, name='index'),
	#lunbo
	url(r'^wheeldata/', wheel_data, name='wheel'),
	url(r'^maindata/', main_data, name='main'),
	url(r'^userdata/', user_data, name='user'),
	#user
    url(r'^register/', register, name='register'),
	url(r'^login/', login, name='login'),
	url(r'^logout/', logout, name='logout'),
	#detail
	url(r'^detail/', jump_to_detail, name='detail'),
	#cart
	url(r'^cart/', jump_to_cart, name='cart'),
	#order
	url(r'^order/', jump_to_order, name='order'),
	url(r'^pay/', jump_to_pay, name='pay'),
	url(r'^topay/', topay,name='topay'),
    url(r'^notify/', notify),
    url(r'^result/', result),
]

LQWeb/LQWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from App.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('App.urls',namespace='App')),
    url(r'',index)
]

LQWeb/App/models.py
from datetime import datetime

from django.db import models

#user
class User(models.Model):
	name = models.CharField(max_length=10,unique=True)
	psd = models.CharField(max_length=100)
	is_delete = models.BooleanField(default=False)
	class Meta:
		db_table = 'lq_user'

#lunbo
class WheelModel(models.Model):
	id = models.AutoField(primary_key=True)
	img = models.CharField(max_length=255)
	class Meta:
		db_table = 'lq_wheel'

#产品模型
#其他产品模型
class OtherPro(models.Model):
	id = models.AutoField(primary_key=True)
	img = models.CharField(max_length=255)
	price = models.FloatField()
	concent = models.CharField(max_length=100)
	class Meta:
		db_table = 'lq_Other'
	
#详情产品模型
class ProModel(models.Model):
	id = models.AutoField(primary_key=True)
	img = models.CharField(max_length=255)
	img1 = models.CharField(max_length=255)
	img2 = models.CharField(max_length=255)
	img3 = models.CharField(max_length=255)
	img4 = models.CharField(max_length=255)
	img5 = models.CharField(max_length=255)
	img6 = models.CharField(max_length=255)
	price = models.FloatField()
	concent = models.CharField(max_length=100)
	concent1 = models.CharField(max_length=100)
	concent2 = models.CharField(max_length=100)
	concent3 = models.CharField(max_length=100)
	concent4 = models.CharField(max_length=100)
	concent5 = models.CharField(max_length=100)
	
	class Meta:
		db_table = 'lq_pro'



#中间表cart
#cart-user（多对一）
#cart-product(一对多)
class Cart(models.Model):
	user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)  # 用户
	goods = models.ForeignKey(ProModel,on_delete=models.SET_NULL,null=True)  # 商品
	ber = models.IntegerField(default=1)  # 商品数量
	is_select = models.BooleanField(default=True)
	class Meta:
		db_table = 'lq_cart'
		
		
class Cart2(models.Model):
	img = models.CharField(max_length=255)
	name = models.CharField(max_length=255)
	ber = models.IntegerField(default=1)
	price = models.FloatField()
	sp = models.FloatField()
	
	class Meta:
		db_table = 'lq_cart2'

class OrderModel(models.Model):
	#下单时间
	order_time = models.CharField(max_length=100)
	#订单号
	order_num = models.CharField(max_length=300)
	#收件人
	get_user = models.CharField(max_length=100)
	#发送地址
	send_address = models.CharField(max_length=200)
	order_pay = models.CharField(max_length=10,default=0)
	class Meta:
		db_table = 'lq_order'

LQWeb/App/views.py
import random

import time
from django.shortcuts import render, redirect,reverse
from App.alipay import AliPay
from App.models import *
from django.http import JsonResponse, HttpResponse

'''
*******************************
         用户
*******************************
'''
#zhuye
def index(request):
	
	return render(request,'zhuye.html')
	
#register
def register(request):
	if request.method == 'GET':
		return render(request, 'zhuce.html')
	
	if request.method == 'POST':
		# 接收前端提交过来的数据
		# value = request.POST.get(name)
		username = request.POST.get('username')
		psd = request.POST.get('pwd1')
		
		# 检查用户名是否已存在
		is_exist = User.objects.filter(name=username).exists()
		if is_exist:
			#如果存在
			return render(request, 'zhuce.html')
		#如果不存在
		# 注册
		user = User()
		user.name = username
		user.psd = psd
		user.save()
		# 注册成功后，自动登录，并跳转到主页
		request.session['user_id'] = user.id
		return redirect(reverse('App:login'))


#login
def login(request):
	
	return render(request, 'denglu.html')
	
		
#logout
def logout(request):
	del request.session['user_name']
	request.session.flush()
	return redirect(reverse('App:index'))

'''
*******************************
         商品详情页
*******************************
'''
def jump_to_detail(request):
	
	return render(request,'spxq.html')
	

'''
*******************************
    购物车/填写订单/订单详情
*******************************
'''
def jump_to_cart(request):
	
	return render(request,'gouwuche.html')

def jump_to_order(request):
	
	return render(request, 'order.html')

def jump_to_pay(request):
	
	if request.method == 'GET':
		return render(request,'order.html')
	
	if request.method == 'POST':
		print('hello')
		get_user = request.POST.get('get_user')
		send_address = request.POST.get('address')
		order_pay = request.POST.get('total_price')
		
		data = {
				'order_time': ran_date2(),
				'order_num': str(ran_date())+str(random_num()),
				'get_user':get_user,
				'send_address':send_address,
				'order_pay':order_pay
		}
		
		#添加订单
		order = OrderModel()
		order.order_time=ran_date2()
		order.order_num = str(ran_date())+str(random_num())
		order.get_user =get_user
		order.send_address = send_address
		order.order_pay = order_pay
		order.save()
		
		order= OrderModel.objects.filter(order_time=order.order_time).last()
		print(order.id)
		return render(request,'pay.html',data,{'order':order})

'''
*******************************
         返回json数据
*******************************
'''
#lunbo
def wheel_data(request):
	wheels = WheelModel.objects.all().values()
	# print(wheels)
	data = list(wheels)
	print(data)
	return JsonResponse({
		'data': data,
		'msg': '获取图片成功'
	})

#楼层floor
def main_data(request):
	
	res = []
	lis1 = []
	pros = ProModel.objects.all().values()
	prolis = list(pros)
	lis1.append(prolis)
	lis2 = []
	others = OtherPro.objects.all().values()
	otherlis = list(others)
	temp = func(otherlis, 6)
	for i in temp:
		# print(i)
		lis2.append(i)
		lis = lis1 + lis2
	# 	# print(lis) #[[],[],[]]
	temp1 = func(lis, 5)
	for s in temp1:
# 		print(s)  #[[],[],[],[],[]],[[],[],[],[],[]]
		res.append(s)
		# print(res)
		
		# with open('1.json', 'w',encoding='utf8') as wf:
		# 	json.dump(res, wf)
		# 	print('ok')
	return JsonResponse({
		'data': res,
		'msg': '获取图片成功'
	})


#userdata
def user_data(request):
	users = User.objects.all().values()
	data = list(users)
	# print(data)
	return JsonResponse({
		'data': data,
		'msg': '获取用户成功'
	})
	

'''
*******************************
            支付宝
*******************************
'''
# 支付
def topay(request):
	#得到新添加的订单
	order = OrderModel.objects.all().last()
	# print(str(order.order_num))
	alipay= AliPay(
        appid="2016100100640327",  # 设置签约的appid
        app_notify_url="http://127.0.0.1:8000/notify/",  # "http://projectsedus.com/",  # 异步支付通知url
        app_private_key_path=r"App/ying_yong_si_yao.txt",  # 设置应用私钥
        alipay_public_key_path=r"App/zhi_fu_bao_gong_yao.txt",  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        debug=True,  # 默认False,            # 设置是否是沙箱环境，True是沙箱环境
        return_url="http://127.0.0.1:8000/result/",  # "http://47.92.87.172:8000/"  # 同步支付通知url
    )

	# 传递参数执行支付类里的direct_pay方法，返回签名后的支付参数，
	url = alipay.direct_pay(
        subject="购物",  # 订单名称
        # 订单号生成，一般是当前时间(精确到秒)+用户ID+随机数
        out_trade_no=order.order_num,  # 订单号
        total_amount=order.order_pay, # 支付金额
        return_url="http://127.0.0.1:8000/result/"  # 支付成功后，跳转url
    )

	# 将前面后的支付参数，拼接到支付网关
    # 注意：下面支付网关是沙箱环境，最终进行签名后组合成支付宝的url请求
	re_url = "https://openapi.alipaydev.com/gateway.do?{data}".format(data=url)
	# print(re_url)
	data = {'re_url': re_url}
	return JsonResponse(data)
	


# 异步支付通知url (上线后使用)
def notify(request):
	
	print("notify:", dict(request.GET))
	return HttpResponse("支付成功:%s" % (dict(request.GET)))


# 付款成功后跳转的url
def result(request):
	print("result:", dict(request.GET))

	# 支付成功后，将对应订单的状态改为：1 已支付

	return HttpResponse("支付成功:%s" % (dict(request.GET)))
'''
*******************************
            辅助功能
*******************************
'''
#列表均分
def func(listTemp, n):
	for i in range(0, len(listTemp), n):
		yield listTemp[i:i + n]

# # 加密
# def my_md5(s):
# 	m = hashlib.md5()
# 	m.update(s.encode())
# 	return m.hexdigest()

#创建函数后必须被调用才能执行
#如以下函数中的print(num)结果，必须要先调用random_num()函数
def random_num():
	j = 5
	
	num = []
	num = ''.join(str(i) for i in random.sample(range(0,9),j))    # sample(seq, n) 从序列seq中选择n个随机且独立的元素；
	print(num)
	return num

	
def ran_date():
	
	sd = time.localtime()
	st = time.strftime('%Y%m%d', sd)
	# str_st = str(st)
	return st

def ran_date2():
	sdd = datetime.now()
	stt = sdd.strftime('%Y-%m-%d %H:%M:%S %A')
	# print(stt)
	#2019-07-27 15:05:02 Saturday
	return stt
	

LQWeb/templates/gouwuche.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" type="text/css" href="/static/css/gouwuche.css"/>
		<script src="/static/js/jquery-1.12.0.js" type="text/javascript" charset="utf-8"></script>
	    <script src="/static/js/jquery.cookie.js" type="text/javascript" charset="utf-8"></script>
	    <script src="/static/js/gouwuche.js" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="Nav">
			<ul class="Navleft">
				<li><img src="/static/img/left_star.jpg" alt="" /></li>
				<li class="firstli"><a href="">收藏本站</a></li>
				<li style="margin-left: 4px;">您好，欢迎来利群商城！</li>
			</ul>
			<ul class="Navright">
				<li style="width: 88px;"><a href="">请</a>
					<span style="display: block;float: right;margin-right: 10px;">
					    <a href="{% url 'App:login' %}" style="color: dodgerblue;">登录</a>
					    <a href="{% url 'App:register' %}" style="color: dodgerblue;">注册</a>
				    </span>
				</li>
				<li><img src="/static/img/mobile.jpg" style="display: block;float: left;margin-left: 10px;margin-top: -5px;"/>手机版</li>
				<li style="width: 90px;"><img src="/static/img/right_star.jpg" alt="" style="display: block;float: left;margin-left: 10px;margin-top: -5px;"/>我的订单</li>
				<li>利群官网</li>
				<li style="border-right: none;" class="Imgli">
					<img src="/static/img/tdcode.jpg" alt="" />
					<img src="/static/img/qq.jpg" alt="" />
					<img src="/static/img/sina.jpg" alt="" />
				</li>
			</ul>
		</div>
		<div class="Img">
			<img src="/static/img/QQ图片20161008104834.png"/>
		</div>
		<div class="car-info">
			<div style="text-align: left;padding: 10px;padding-left:15px;font-size: 13px;">
				<input type="checkbox" checked="checked"/>
			                     供应商：
				<font style="color: #E03941; font-weight: bold;">利群商城</font>
			</div>
			<div class="tbody">
				<table border="0" cellspacing="1" cellpadding="0" id="table" style="width: 998px;background: #CCCCCC;height: 35px;font-size: 12px;">
					<tbody>
						<tr align="center">

							<td width="310px;"hheight="20px;"><span style="display: block;float: left;margin-left: 9px;"><input type="checkbox" style="display: block;float: left;margin-left: 5px;" id="buton"/>:全选 </span> 商品名称</td>
							<td width="115px;">商城单价</td>
							<td width="120px;">商品数量</td>
							<td width="95px;">小计</td>
							<td width="90px;">积分数额</td>
							<td width="100px;">您的可选操作</td>
							<td width="168px;">其它说明</td>
						</tr>
					</tbody>
				</table>

			    <div class="tttt">

			    </div>

				<table border="0" cellspacing="1" cellpadding="0"style="width: 998px;background: #CCCCCC;height: 35px;font-size: 12px;">
					<tbody>
						<tr>
							<td colspan="7"height="33">
								<div style="float: right; line-height: 30px;margin-right: 30px;">
			                                                                                    已选择该供应商的 <span style="color: #D21D16; font-weight: bold;"id="NUM">0</span>  件商品    &nbsp;总重量：0.36kg &nbsp;总价（不含邮费）：
                                        <span style="color: #D21D16; font-weight: bold;" id="PRI">￥0.00</span>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="foor">
			<div class="mess">
				<span style="float: right; line-height: 35px; height: 35px; color: black; width: 310px;text-align: left;font-size: 12px;">
					已选  <font id="check_acount" style="font-weight: bold; color: #CC0809;">0</font>&nbsp;件商品&nbsp;总价(不含运费)：
					<font id="check_allacount" style="color: #CC0809;font-size: 20px; font-weight: bolder;">￥0.00</font>
				</span>
			</div>
			<div style="width: 130px; height: 35px; overflow: hidden; float: left;">
				<a href="{% url 'App:index' %}">
					<img src="/static/img/continue_buy.jpg" alt="" />
				</a>
			</div>
			<div style="width: 125px; height: 35px; overflow: hidden; float: left;">
				<a href="{% url 'App:order' %}">
					<img src="/static/img/shopcart_buy_03.jpg" alt="" />
				</a>
			</div>
		</div>
		<div class="FootRAM">
				<div class="Footroll">
					<ul class="footmin">
						<li>关于我们</li>
						<li>联系我们</li>
						<li>诚聘英才</li>
						<li>手机利群</li>
						<li>销售联盟</li>
						<li>友情连接</li>
						<li>网站合作</li>
						<li>帮助中心</li>
						<li class="rolllast">版权说明</li>
					</ul>
					<ul class="footbig">
						<li>利群集团</li>
						<li>百货集团</li>
						<li>利群网</li>
						<li>利群酒店</li>
						<li>利群房地产</li>
						<li>利群旅行社</li>
						<li>利群药品</li>
						<li>利群影城</li>
						<li>利群水站</li>
						<li class="rolllast">利群家政</li>
					</ul>
					<p>鲁ICP证09054331号-2 Copyright©2004-2015 利群集团青岛电子商务有限公司 版权所有</p>
				</div>

			</div>
</body>
</html>

LQWeb/templates/order.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" type="text/css" href="/static/css/order.css"/>
		<script src="/static/js/jquery-1.12.0.js" type="text/javascript" charset="utf-8"></script>
	    <script src="/static/js/jquery.cookie.js" type="text/javascript" charset="utf-8"></script>
	    <script src="/static/js/order.js" type="text/javascript" charset="utf-8"></script>
	</head>
	<body>
		<div class="Nav">
			<ul class="Navleft">
				<li><img src="/static/img/left_star.jpg" alt="" /></li>
				<li class="firstli"><a href="">收藏本站</a></li>
				<li style="margin-left: 4px;">您好，欢迎来利群商城！</li>
			</ul>
			<ul class="Navright">
				<li style="width: 88px;"><a href="">请</a>
					<span style="display: block;float: right;margin-right: 10px;">
					    <a href="{% url 'App:login' %}" style="color: dodgerblue;">登录</a>
					    <a href="{% url 'App:register' %}" style="color: dodgerblue;">注册</a>
				    </span>
				</li>
				<li><img src="/static/img/mobile.jpg" style="display: block;float: left;margin-left: 10px;margin-top: -5px;"/>手机版</li>
				<li style="width: 90px;"><img src="/static/img/right_star.jpg" alt="" style="display: block;float: left;margin-left: 10px;margin-top: -5px;"/>我的订单</li>
				<li>利群官网</li>
				<li style="border-right: none;" class="Imgli">
					<img src="/static/img/tdcode.jpg" alt="" />
					<img src="/static/img/qq.jpg" alt="" />
					<img src="/static/img/sina.jpg" alt="" />
				</li>
			</ul>
		</div>
		<div class="Img">
			<img src="/static/img/QQ图片20161008104834.png"/>
		</div>
    <form action="{% url 'App:pay' %}" method="post">
        {% csrf_token %}
		<div class="car-info">
			<div style="text-align: left;padding: 10px;padding-left:15px;font-size: 13px;">
{#				<input type="checkbox" checked="checked"/>#}
                <span>收件人：</span>
                <input type="text" name="get_user" />
                <span>邮寄地址：</span>
                <input type="text" name="address" />
                <span>消费价格：</span>
                <input type="text" name="total_price" id="total_price" readonly/>元
{#               <span>订单号:</span>#}
{#				<font style="color: #E03941; font-weight: bold;">{{ order_num }}</font>#}
{#               <span>邮寄地址:</span>#}
{#				<font style="color: #E03941; font-weight: bold;">深圳市西部硅谷5楼1903</font>#}
{#			     <span>订单时间：</span>#}
{#				<font style="color: #E03941; font-weight: bold;">{{ date_time }}</font>#}

            </div>

			<div class="tbody">
				<table border="0" cellspacing="1" cellpadding="0" id="table" style="width: 998px;background: #CCCCCC;height: 35px;font-size: 12px;">
					<tbody>
						<tr align="center">

							<td width="310px;"hheight="20px;"><span style="display: block;float: left;margin-left: 9px;"><input type="checkbox" style="display: block;float: left;margin-left: 5px;" id="buton"/>:全选 </span> 商品名称</td>
							<td width="115px;">商城单价</td>
							<td width="120px;">商品数量</td>
							<td width="95px;">小计</td>
							<td width="90px;">买家用户名</td>
							<td width="100px;">您的可选操作</td>
							<td width="168px;">其它说明</td>
						</tr>
					</tbody>
				</table>

			    <div class="tttt">

			    </div>

				<table border="0" cellspacing="1" cellpadding="0"style="width: 998px;background: #CCCCCC;height: 35px;font-size: 12px;">
					<tbody>
{#						<tr>#}
{#							<td colspan="7"height="33">#}
{#								<div style="float: right; line-height: 30px;margin-right: 30px;">#}
{#			                                                                                    该用户已选择 <span style="color: #D21D16; font-weight: bold;"id="NUM">0</span>  件商品    &nbsp;总重量：0.36kg &nbsp;总价（不含邮费）：#}
{#                                        <span style="color: #D21D16; font-weight: bold;" id="PRI">￥0.00</span>#}
{#								</div>#}
{#							</td>#}
{#						</tr>#}
					</tbody>
				</table>
			</div>
		</div>
		<div class="foor">
			<div class="mess">
				<span style="float: right; line-height: 35px; height: 35px; color: black; width: 310px;text-align: left;font-size: 12px;">
					已选  <font id="check_acount" style="font-weight: bold; color: #CC0809;">0</font>&nbsp;件商品&nbsp;总价(不含运费)：
					<font id="check_allacount" style="color: #CC0809;font-size: 20px; font-weight: bolder;">￥0.00</font>

				</span>
			</div>
			<div style="width: 130px; height: 35px; overflow: hidden; float: left;">
				<a href="{% url 'App:index' %}">
					<img src="/static/img/continue_buy.jpg" alt="" />
				</a>
			</div>
{#			<div style="width: 125px; height: 35px; overflow: hidden; float: left;">#}
{#				<a href="#">#}
{#					<img src="/static/img/shopcart_buy_01.jpg" alt="" />#}
{#				</a>#}
{#			</div>#}
            <input type="image" src="/static/img/shopcart_buy_04.jpg" style="width: 125px; height: 35px; overflow: hidden; float: left;"/>
		</div>
    </form>
		<div class="FootRAM">
				<div class="Footroll">
					<ul class="footmin">
						<li>关于我们</li>
						<li>联系我们</li>
						<li>诚聘英才</li>
						<li>手机利群</li>
						<li>销售联盟</li>
						<li>友情连接</li>
						<li>网站合作</li>
						<li>帮助中心</li>
						<li class="rolllast">版权说明</li>
					</ul>
					<ul class="footbig">
						<li>利群集团</li>
						<li>百货集团</li>
						<li>利群网</li>
						<li>利群酒店</li>
						<li>利群房地产</li>
						<li>利群旅行社</li>
						<li>利群药品</li>
						<li>利群影城</li>
						<li>利群水站</li>
						<li class="rolllast">利群家政</li>
					</ul>
					<p>鲁ICP证09054331号-2 Copyright©2004-2015 利群集团青岛电子商务有限公司 版权所有</p>
				</div>

			</div>
</body>
</html>

LQWeb/templates/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h3>支付</h3>
        <hr>

        <p>下单时间：{{ order_time }}</p>
        <p>商品订单号：{{ order_num }}</p>
        <p>消费金额：{{ order_pay }}元</p>
        <p>收件人：{{ get_user }}</p>
        <p>邮寄地址：{{ send_address }}</p>
        <hr>
        <button type="button" id="pay">支付</button>
<!--        {% load static %}-->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/pay.js"></script>


{#       <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <input type="image" id="pay" src="/static/img/shopcart_buy_01.jpg" style="width: 125px; height: 35px; overflow: hidden; float: left;">#}
{#        </form>#}
</body>
</html>